# Generated by Django 5.2.6 on 2025-10-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusProficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(unique=True)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estadistica_asociada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Page', models.CharField(blank=True, max_length=150, null=True)),
                ('Rarity', models.CharField(blank=True, max_length=150, null=True)),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
                ('Attunement', models.CharField(blank=True, max_length=200, null=True)),
                ('Damage', models.CharField(blank=True, max_length=150, null=True)),
                ('Properties', models.TextField(blank=True, null=True)),
                ('Mastery', models.CharField(blank=True, max_length=200, null=True)),
                ('Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Value', models.CharField(blank=True, max_length=150, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(default='', max_length=60)),
                ('treasure_points', models.IntegerField(default=0)),
                ('oro', models.IntegerField(default=0)),
                ('tiempo_libre', models.IntegerField(default=0)),
                ('clase', models.CharField(blank=True, choices=[('BARBARIAN', 'Barbarian'), ('BARD', 'Bard'), ('WARLOCK', 'Warlock'), ('CLERIC', 'Cleric'), ('DRUID', 'Druid'), ('RANGER', 'Ranger'), ('FIGHTER', 'Fighter'), ('SORCERER', 'Sorcerer'), ('WIZARD', 'Wizard'), ('MONK', 'Monk'), ('PALADIN', 'Paladin'), ('ROGUE', 'Rogue')], max_length=30)),
                ('treasure_points_gastados', models.IntegerField(default=0, null=True)),
                ('nivel', models.IntegerField(default=1, null=True)),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('faccion', models.CharField(blank=True, max_length=50)),
                ('fuerza', models.IntegerField(default=10)),
                ('inteligencia', models.IntegerField(default=10)),
                ('sabiduria', models.IntegerField(default=10)),
                ('destreza', models.IntegerField(default=10)),
                ('constitucion', models.IntegerField(default=10)),
                ('carisma', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_proficiente', models.BooleanField(default=False)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencias', to='api.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_final', models.IntegerField(default=1, null=True)),
                ('es_magico', models.BooleanField(default=False)),
                ('oro_necesario', models.IntegerField(default=0)),
                ('dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Medio', 'Medio'), ('Dificil', 'Difícil'), ('Muy dificil', 'Muy Difícil'), ('Oculto', 'Oculto')], default='F', max_length=15)),
                ('objeto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='api.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rango_maximo', models.IntegerField(default=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisito_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.personaje')),
            ],
            options={
                'unique_together': {('personaje', 'objeto')},
            },
        ),
    ]
