# Generated by Django 5.2.6 on 2025-11-21 03:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusProficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(unique=True)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DnDClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Artificer', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('hit_die', models.IntegerField(choices=[(6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')], default=8)),
                ('primary_ability', models.CharField(choices=[('fuerza', 'Fuerza'), ('destreza', 'Destreza'), ('constitucion', 'Constitución'), ('inteligencia', 'Inteligencia'), ('sabiduria', 'Sabiduría'), ('carisma', 'Carisma')], default='fuerza', help_text="Estadística principal de la clase (ej. 'inteligencia' para Artificer).", max_length=20)),
                ('saving_throws', models.JSONField(default=list, help_text='Lista de campos de estadística para salvaciones.')),
                ('skill_choices_count', models.PositiveIntegerField(default=2)),
                ('armor_proficiencies', models.TextField(blank=True, help_text='Ej: Light and Medium armor, Shields')),
                ('weapon_proficiencies', models.TextField(blank=True, help_text='Ej: Simple weapons, firearms')),
                ('tool_proficiencies', models.TextField(blank=True, help_text="Ej: Thieves' tools, tinker's tools")),
                ('starting_equipment', models.TextField(blank=True, help_text='Descripción del equipo inicial.')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estadistica_asociada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Page', models.CharField(blank=True, max_length=150, null=True)),
                ('Rarity', models.CharField(blank=True, max_length=150, null=True)),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
                ('Attunement', models.CharField(blank=True, max_length=200, null=True)),
                ('Damage', models.CharField(blank=True, max_length=150, null=True)),
                ('Properties', models.TextField(blank=True, null=True)),
                ('Mastery', models.CharField(blank=True, max_length=200, null=True)),
                ('Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Value', models.CharField(blank=True, max_length=150, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('es_investigable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="El nombre completo de la especie (ej. 'Aarakocra (New World Ancestry)')", max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Versión amigable para URLs del nombre (se genera automáticamente)', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Texto de ambientación (lore) o descripción general de la especie.')),
                ('creature_type', models.CharField(choices=[('Humanoid', 'Humanoide'), ('Elemental', 'Elemental'), ('Monstrosity', 'Monstruosidad'), ('Fey', 'Feérico'), ('Fiend', 'Infernal'), ('Celestial', 'Celestial'), ('Dragon', 'Dragón'), ('Giant', 'Gigante'), ('Aberration', 'Aberración'), ('Beast', 'Bestia'), ('Construct', 'Constructo'), ('Ooze', 'Limo'), ('Plant', 'Planta'), ('Undead', 'No-muerto')], default='Humanoid', help_text='El tipo de criatura (ej. Humanoide, Elemental).', max_length=50)),
                ('size', models.CharField(choices=[('Tiny', 'Diminuto'), ('Small', 'Pequeño'), ('Medium', 'Mediano'), ('Small or Medium', 'Pequeño o Mediano'), ('Medium or Large', 'Mediano o Grande'), ('Large', 'Grande'), ('Huge', 'Enorme'), ('Gargantuan', 'Gargantuesco')], default='Medium', help_text='El tamaño de la criatura (ej. Mediano, Pequeño o Mediano).', max_length=50)),
                ('walking_speed', models.PositiveIntegerField(default=30, help_text='Velocidad base de movimiento en pies.')),
                ('darkvision', models.PositiveIntegerField(default=0, help_text='Rango de la visión en la oscuridad en pies (0 si no tiene).')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_type', models.CharField(default='Fixed', max_length=20)),
                ('quantity_stat', models.CharField(blank=True, max_length=20, null=True)),
                ('progression', models.JSONField(blank=True, default=dict)),
                ('value_progression', models.JSONField(blank=True, default=dict)),
                ('reset_on', models.CharField(default='Long Rest', max_length=50)),
                ('dnd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.dndclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dnd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.dndclass')),
            ],
            options={
                'ordering': ['level', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='DnDFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('feat_type', models.CharField(choices=[('Origin', 'Origin'), ('General', 'General'), ('Epic Boon', 'Epic Boon'), ('Fighting Style', 'Fighting Style')], default='General', max_length=20)),
                ('description', models.TextField(help_text='Flavor text o descripción general.')),
                ('source', models.CharField(default='PHB', max_length=100)),
                ('prerequisite_level', models.PositiveIntegerField(default=0, help_text='Nivel mínimo (ej. 4). 0 si no tiene.')),
                ('prerequisite_text', models.CharField(blank=True, help_text="Texto manual de requisitos (ej. 'Str 13+', 'Spellcasting feature').", max_length=255)),
                ('ability_score_increase', models.TextField(blank=True, help_text='Texto describiendo qué stats suben.')),
                ('repeatable', models.BooleanField(default=False, help_text='¿Se puede tomar este dote más de una vez?')),
                ('prerequisite_feat', models.ForeignKey(blank=True, help_text='Si requiere tener otro dote previo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_feats', to='api.dndfeat')),
                ('prerequisite_species', models.ForeignKey(blank=True, help_text='Si requiere una especie específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_feats', to='api.species')),
            ],
        ),
        migrations.CreateModel(
            name='FeatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('choices_count', models.PositiveIntegerField(default=0, help_text='Cuántas opciones elegir (Ej: 1 para Giant Heritage).')),
                ('dnd_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.dndfeat')),
                ('parent_feature', models.ForeignKey(blank=True, help_text="Si este rasgo es una opción (ej. 'Cloud Giant'), selecciona su padre ('Giant Bless').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.featfeature')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DnDSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(default='PHB', max_length=100)),
                ('skill_choices_count', models.PositiveIntegerField(default=0, help_text='Si es 0, se otorgan todas. Si es > 0, el jugador elige.')),
                ('bonus_proficiencies', models.TextField(blank=True, help_text='Texto libre para herramientas, idiomas o armas extra.')),
                ('dnd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='api.dndclass')),
                ('skill_choices', models.ManyToManyField(blank=True, help_text='Habilidades adicionales que otorga la subclase (o opciones).', related_name='subclass_options', to='api.habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='dndclass',
            name='skill_choices',
            field=models.ManyToManyField(blank=True, help_text='Qué habilidades puede elegir el jugador.', related_name='class_options', to='api.habilidad'),
        ),
        migrations.CreateModel(
            name='ObjetoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=1, help_text='Cantidad de este objeto disponible en la tienda.')),
                ('precio_personalizado', models.IntegerField(blank=True, help_text='Precio de venta en oro. Si se deja en blanco, se podría usar el valor base del objeto.', null=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(default='', max_length=60)),
                ('nivel', models.IntegerField(default=1)),
                ('faccion', models.CharField(blank=True, max_length=50)),
                ('treasure_points', models.IntegerField(default=0)),
                ('treasure_points_gastados', models.IntegerField(default=0, null=True)),
                ('oro', models.IntegerField(default=0)),
                ('tiempo_libre', models.IntegerField(default=0)),
                ('fuerza', models.IntegerField(default=10)),
                ('inteligencia', models.IntegerField(default=10)),
                ('sabiduria', models.IntegerField(default=10)),
                ('destreza', models.IntegerField(default=10)),
                ('constitucion', models.IntegerField(default=10)),
                ('carisma', models.IntegerField(default=10)),
                ('clase', models.ForeignKey(blank=True, help_text='Clase principal del personaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='api.dndclass')),
                ('dotes', models.ManyToManyField(blank=True, help_text='Dotes adquiridos (Origen, Nivel 4, etc.)', related_name='personajes', to='api.dndfeat')),
                ('subclase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='api.dndsubclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='api.species')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partys_creadas', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='partys', to='api.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_herramienta', models.CharField(max_length=100)),
                ('grado', models.CharField(choices=[('Novato', 'Novato'), ('Aprendiz', 'Aprendiz'), ('Experto', 'Experto'), ('Maestro Artesano', 'Maestro Artesano'), ('Gran Maestro', 'Gran Maestro')], default='Novato', max_length=20)),
                ('exitos_acumulados', models.IntegerField(default=0)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_herramientas', to='api.personaje')),
            ],
            options={
                'verbose_name_plural': 'Competencias con Herramientas',
                'unique_together': {('personaje', 'nombre_herramienta')},
            },
        ),
        migrations.CreateModel(
            name='Proficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_proficiente', models.BooleanField(default=False)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencias', to='api.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oro_acumulado', models.IntegerField(default=0)),
                ('exitos_conseguidos', models.IntegerField(default=0)),
                ('exitos_requeridos', models.IntegerField(default=0)),
                ('dias_trabajados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pausado', 'Pausado')], default='en_progreso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('competencia_utilizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='api.competenciaherramienta')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_recetas', to='api.personaje')),
            ],
            options={
                'verbose_name_plural': 'Progresos de Recetas',
            },
        ),
        migrations.CreateModel(
            name='HistorialTirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_dado', models.IntegerField()),
                ('modificador', models.IntegerField()),
                ('resultado_total', models.IntegerField()),
                ('exito', models.BooleanField()),
                ('oro_sumado', models.IntegerField(default=0)),
                ('oro_gastado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiradas', to='api.progresoreceta')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_final', models.IntegerField(default=1, null=True)),
                ('es_magico', models.BooleanField(default=False)),
                ('herramienta', models.CharField(blank=True, max_length=100, null=True)),
                ('oro_necesario', models.IntegerField(default=0, help_text='Solo para objetos no mágicos. Los mágicos usan costes fijos según rareza.')),
                ('grado_minimo_requerido', models.CharField(choices=[('Novato', 'Novato'), ('Aprendiz', 'Aprendiz'), ('Experto', 'Experto'), ('Maestro Artesano', 'Maestro Artesano'), ('Gran Maestro', 'Gran Maestro')], default='Novato', help_text='Solo para objetos no mágicos. Para mágicos se determina automáticamente por rareza.', max_length=20)),
                ('rareza', models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very Rare', 'Very Rare'), ('Legendary', 'Legendary')], help_text='Solo para objetos mágicos. Determina DC, éxitos, coste y grado mínimo.', max_length=15, null=True)),
                ('es_consumible', models.BooleanField(default=False, help_text='Si es un consumible mágico (DC más baja)')),
                ('material_raro', models.ForeignKey(blank=True, help_text='Material especial necesario para objetos mágicos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_como_material_raro', to='api.objeto')),
                ('objeto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='api.objeto')),
            ],
        ),
        migrations.AddField(
            model_name='progresoreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receta'),
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='SubclassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.PositiveIntegerField(default=3, help_text='Nivel de CLASE en que se gana.')),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('choices_count', models.PositiveIntegerField(default=0, help_text='Cuántas opciones elegir (Ej: 3 para Maniobras iniciales).')),
                ('dnd_subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.dndsubclass')),
                ('parent_feature', models.ForeignKey(blank=True, help_text='Si este rasgo es una opción (ej. una Maniobra), selecciona el rasgo padre.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.subclassfeature')),
            ],
            options={
                'ordering': ['level', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubclassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Superiority Dice', max_length=100)),
                ('quantity_type', models.CharField(default='Fixed', max_length=20)),
                ('quantity_stat', models.CharField(blank=True, max_length=20, null=True)),
                ('progression', models.JSONField(blank=True, default=dict, help_text="{ '3': 4, '7': 5 }")),
                ('value_progression', models.JSONField(blank=True, default=dict, help_text="{ '3': 'd8', '10': 'd10' }")),
                ('reset_on', models.CharField(default='Short Rest', max_length=50)),
                ('dnd_subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.dndsubclass')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('npc_asociado', models.CharField(blank=True, help_text='Nombre del NPC que regenta la tienda.', max_length=100)),
                ('objetos', models.ManyToManyField(blank=True, related_name='tiendas', through='api.ObjetoTienda', to='api.objeto')),
            ],
        ),
        migrations.AddField(
            model_name='objetotienda',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.tienda'),
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rango_maximo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('beneficio', models.TextField(blank=True, null=True)),
                ('requisito_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dias_trabajados', models.PositiveIntegerField(default=1)),
                ('bono_economia', models.IntegerField(default=0)),
                ('desempenio', models.FloatField(default=1.0, help_text='Multiplicador de desempeño (ej: 0.5 a 2.0)')),
                ('pago_total', models.FloatField(default=0, editable=False)),
                ('modificador_estadistica', models.IntegerField(default=0)),
                ('bonus_proficiencia', models.IntegerField(default=0)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personaje')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="El nombre del rasgo (ej. 'Wind Caller', 'Chikcha Legacy', 'Natural Armor').", max_length=200)),
                ('description', models.TextField(help_text='La descripción completa y las reglas del rasgo.')),
                ('min_choices', models.PositiveIntegerField(default=0, help_text="Para un rasgo 'padre', el número MÍNIMO de opciones a elegir (ej. 2 para Chikcha Legacy).")),
                ('max_choices', models.PositiveIntegerField(default=0, help_text="Para un rasgo 'padre', el número MÁXIMO de opciones a elegir (ej. 2 para Chikcha Legacy).")),
                ('display_order', models.PositiveIntegerField(default=10, help_text='Orden para mostrar los rasgos. Menor número primero.')),
                ('parent_choice', models.ForeignKey(blank=True, help_text="Si este rasgo es una *opción* seleccionable (ej. 'Natural Armor'), conéctalo aquí al rasgo 'padre' (ej. 'Chikcha Legacy').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.trait')),
                ('species', models.ForeignKey(help_text='La especie a la que pertenece este rasgo.', on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='api.species')),
            ],
            options={
                'verbose_name': 'Trait',
                'verbose_name_plural': 'Traits',
                'ordering': ['species', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonajeEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_feature_elegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elegido_por', to='api.featfeature')),
                ('origen_class_feature', models.ForeignKey(blank=True, help_text='Si viene de una Clase (ej. Fighting Style)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classfeature')),
                ('origen_feat_feature', models.ForeignKey(blank=True, help_text='Si viene de un Dote (ej. Giant Bless)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.featfeature')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elecciones', to='api.personaje')),
                ('origen_subclass_feature', models.ForeignKey(blank=True, help_text='Si viene de una Subclase (ej. Maniobras)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subclassfeature')),
                ('subclass_feature_elegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elegido_por', to='api.subclassfeature')),
                ('origen_trait', models.ForeignKey(blank=True, help_text='Si la elección viene de una Especie (ej. Giant Ancestry)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trait')),
                ('trait_elegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elegido_por', to='api.trait')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_party', to='api.party')),
                ('donado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personaje')),
            ],
            options={
                'unique_together': {('party', 'objeto')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.personaje')),
            ],
            options={
                'unique_together': {('personaje', 'objeto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='objetotienda',
            unique_together={('tienda', 'objeto')},
        ),
        migrations.CreateModel(
            name='ProgresoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_actual', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dias_acumulados_rango', models.PositiveIntegerField(default=0)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_trabajos', to='api.personaje')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_personajes', to='api.trabajo')),
            ],
            options={
                'unique_together': {('personaje', 'trabajo')},
            },
        ),
        migrations.CreateModel(
            name='PagoRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('valor_suma', models.FloatField(help_text='Valor que se suma al bono de economía (ej: 1, 2, 3...)')),
                ('multiplicador', models.FloatField(help_text='Multiplicador base del trabajo (ej: 1.25, 3.75, 7.5...)')),
                ('dias_para_siguiente_rango', models.PositiveIntegerField(default=50)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.trabajo')),
            ],
            options={
                'unique_together': {('trabajo', 'rango')},
            },
        ),
    ]
