# Generated by Django 5.2.6 on 2025-09-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Page', models.CharField(blank=True, max_length=150, null=True)),
                ('Rarity', models.CharField(blank=True, max_length=150, null=True)),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
                ('Attunement', models.CharField(blank=True, max_length=200, null=True)),
                ('Damage', models.CharField(blank=True, max_length=150, null=True)),
                ('Properties', models.TextField(blank=True, null=True)),
                ('Mastery', models.CharField(blank=True, max_length=200, null=True)),
                ('Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Value', models.CharField(blank=True, max_length=150, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('nombre_personaje', models.CharField(default='', max_length=60)),
                ('treasure_points', models.IntegerField(default=0)),
                ('oro', models.IntegerField(default=0)),
                ('tiempo_libre', models.IntegerField(default=0)),
                ('clase', models.CharField(blank=True, choices=[('BARBARIAN', 'Barbarian'), ('BARD', 'Bard'), ('WARLOCK', 'Warlock'), ('CLERIC', 'Cleric'), ('DRUID', 'Druid'), ('RANGER', 'Ranger'), ('FIGHTER', 'Fighter'), ('SORCERER', 'Sorcerer'), ('WIZARD', 'Wizard'), ('MONK', 'Monk'), ('PALADIN', 'Paladin'), ('ROGUE', 'Rogue')], max_length=30)),
                ('treasure_points_gastados', models.IntegerField(default=0, null=True)),
                ('nivel', models.IntegerField(default=1, null=True)),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('faccion', models.CharField(blank=True, max_length=50)),
            ],
        )
    ]
