# Generated by Django 5.2.6 on 2025-10-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receta_ingredientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusProficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(unique=True)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estadistica_asociada', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personaje',
            name='carisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personaje',
            name='constitucion',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personaje',
            name='destreza',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personaje',
            name='fuerza',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personaje',
            name='inteligencia',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personaje',
            name='sabiduria',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Proficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_proficiente', models.BooleanField(default=False)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencias', to='api.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rango_maximo', models.IntegerField(default=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisito_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad')),
            ],
        ),
    ]
