# Generated by Django 5.2.6 on 2025-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bonusproficiencia_habilidad_personaje_carisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(choices=[('Facil', 'Fácil'), ('Medio', 'Medio'), ('Dificil', 'Difícil'), ('Muy dificil', 'Muy Difícil'), ('Oculto', 'Oculto')], default='F', max_length=15),
        ),
        migrations.AddField(
            model_name='receta',
            name='es_magico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receta',
            name='oro_necesario',
            field=models.IntegerField(default=0),
        ),
    ]
