# Generated by Django 5.2.6 on 2025-10-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_personaje_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.personaje')),
            ],
            options={
                'unique_together': {('personaje', 'objeto')},
            },
        ),
    ]
