from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(BonusProficiencia)
admin.site.register(DnDClass)
admin.site.register(Habilidad)
admin.site.register(Objeto)
admin.site.register(Species)
admin.site.register(ClassResource)
admin.site.register(ClassFeature)
admin.site.register(DnDFeat)
admin.site.register(FeatFeature)
admin.site.register(DnDSubclass)
admin.site.register(ObjetoTienda)
admin.site.register(Personaje)
admin.site.register(Party)
admin.site.register(CompetenciaHerramienta)
admin.site.register(Proficiencia)
admin.site.register(ProgresoReceta)
admin.site.register(HistorialTirada)
admin.site.register(Receta)
admin.site.register(Ingredientes)
admin.site.register(SubclassFeature)
admin.site.register(SubclassResource)
admin.site.register(Tienda)
admin.site.register(Trabajo)
admin.site.register(TrabajoRealizado)
admin.site.register(Trait)
admin.site.register(PersonajeEleccion)
admin.site.register(InventarioParty)
admin.site.register(Inventario)
admin.site.register(ProgresoTrabajo)
admin.site.register(PagoRango)