import type { Metadata } from "next";
import { Inter, Cinzel } from "next/font/google";
import "../styles/globals.css";
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "700"],
});

const cinzel = Cinzel({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cinzel", 
  weight: ["600", "800"],
});

export const metadata: Metadata = {
  title: "UI Kit - West Marches",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className={`${inter.variable} ${cinzel.variable}`}>
      <body>
        <AuthProvider> {/* <-- Envuelve a los children */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
