import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Cinzel } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "700"],
});

const cinzel = Cinzel({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cinzel", 
  weight: ["600", "800"],
});

export const metadata: Metadata = {
  title: "UI Kit - West Marches",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${inter.variable} ${cinzel.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
