services:
  - type: web
    name: dbn-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: daphne backend.asgi:application --port $PORT --bind 0.0.0.0
    rootDir: backend
    plan: free